"""Prometheus Research MCP Server."""

import json
import logging

from mcp.server.fastmcp import FastMCP

from prometheus.services.tavily_search import search

logger = logging.getLogger(__name__)


mcp = FastMCP(
    "prometheus-research",
    instructions=(
        "Web research tools for investment research. "
        "Provides web search capabilities to execute research plans "
        "generated by the analysis server."
    ),
)


@mcp.tool()
async def web_search(
    search_term: str,
    objective: str | None = None,
) -> str:
    """Search the web for financial research information.

    Executes a web search using the provided search term and returns
    structured results. Use this after generating a research plan to
    execute each search.

    Args:
        search_term: The search query to execute.
        objective: Optional description of what you hope to learn from
                   this search. Does not affect search results but provides
                   context for result interpretation.
    """
    response = search(query=search_term)

    results = []
    for result in response.get("results", []):
        results.append(
            {
                "title": result.get("title", ""),
                "url": result.get("url", ""),
                "content": result.get("content", ""),
            }
        )

    output = {
        "search_term": search_term,
        "results": results,
    }
    if objective is not None:
        output["objective"] = objective

    return json.dumps(output, indent=2)


def main() -> None:
    """Run the Research MCP server."""
    logger.info("Starting Prometheus Research MCP server")
    mcp.run()


if __name__ == "__main__":
    main()
